// Canton Domain Manager Configuration

include required("storage.conf")
include required("tls.conf")
include required("monitoring.conf")

canton {
  domain-managers {
    domain-manager1 {
      storage = ${_shared_storage}
      storage.config.properties.databaseName = "canton_domain_manager"
      storage.config.properties.databaseName = ${?CANTON_DOMAIN_MANAGER_DB}

      admin-api {
        address = "127.0.0.1"
        port = 5016
        port = ${?CANTON_DOMAIN_MANAGER_ADMIN_PORT}

        tls = ${_tls_config}
      }
    }
  }
}
